### PR TITLE
Fix : Improve Home Page Design and Add Branding

### LINKED ISSUE #4: [Front] Improve Home Page Design and Add Branding
**Description**
---
Enhance the Home Page  to include better styling, a logo, and a professional look. The page should act as a welcoming entry point for the dApp while maintaining simplicity.

**Acceptance Criteria**
---

- [ ] Add a logo or placeholder image at the top of the Home Page.
- [ ] Add descriptive text explaining the purpose of the dApp in a visually appealing format.
- [ ] Improve the overall styling, Use TailwindCSS and [dapp](https://github.com/Carbonable/carbonable-home) as an example.

**Additional context**
---
[ Easy Difficulty - Frontend ]

### PR DESCRIPTION
**Pull request by SudiptaPaul-31**
Fixes #4  

Changes :

- Made the landing page/ homepage as requested

### CODE REVIEW

**Comment by SudiptaPaul-31** [comment]
@julienbrs please review

**Comment by julienbrs** [comment]
Kindly asking to review the front design @schwepps  please :pray:

**Comment by schwepps** [comment]
Hey @SudiptaPaul-31! Great job.
Could you just apply the same colors as in our dapp?
Here is the tailwind config to achieve that:
`colors: {
  neutral: {
    100: '#D0D1D6',
    200: '#A8ABB3',
    300: '#878A94',
    400: '#555861',
    500: '#363840',
    600: '#2B2E36',
    700: '#1F2128',
    800: '#13151C',
    900: '#0B0D13',
  },
  greenish: {
    100: '#DDF6EB',
    200: '#BAEED7',
    300: '#75D9AD',
    400: '#47C48E',
    500: '#29A46F',
    600: '#22875B',
    700: '#1B6B49',
    800: '#145136',
    900: '#0E3725',
    1000: '#082015',
  },
  opacityLight: {
    5: 'rgba(208, 209, 214, 0.05)',
    10: 'rgba(208, 209, 214, 0.1)',
    20: 'rgba(208, 209, 214, 0.2)',
    30: 'rgba(208, 209, 214, 0.3)',
    60: 'rgba(208, 209, 214, 0.6)',
    70: 'rgba(208, 209, 214, 0.7)',
    80: 'rgba(208, 209, 214, 0.8)',
    90: 'rgba(208, 209, 214, 0.9)',
  },
},`

neutral-100 is for text, neutral-300 for secondary text, greenish-500 is the primary color for action button of text emphasis.
neutral-800 is body background.
opacityLight-5 and 10 for borders and backgrounds.

**Comment by SudiptaPaul-31** [comment]
@schwepps Please have a review 

image

**Review by schwepps — APPROVED** [review]
All good! Thanks @SudiptaPaul-31 !

**Pull request merged**
