### PR TITLE
refact: refactor dashboard to display NFT metadata

### LINKED ISSUE #3: [ Front ] Refactor Dashboard to Display NFT Metadata Linked to Locks
**Description**
---
Enhance the `Dashboard` to display NFTs received for locked tokens, using mock data for now. Each NFT should contain metadata reflecting the details of the corresponding lock (e.g., Token ID, Amount, Duration).

**Acceptance Criteria**
---

- [ ] Refactor `Dashboard` to display NFT metadata in a visually structured format.
- [ ] Link each NFT to its corresponding lock in the mock data.
- [ ] Create a better reusable `NFTCard` component to display NFT metadata:
  - NFT ID
  - Lock details (Token ID, Amount, Duration)
- [ ] Replace the plain list of NFTs with a styled grid of `NFTCard` components.

**Additional context**
---
The `NFTCard` should dynamically reflect mock metadata associated with each NFT. This prepares the Dashboard for real contract data in the future.

**Hints for Mock Data:**
You can improve the existing `useMockData` hook to include more detailed and realistic NFT metadata. Here's a suggested structure for the mock data:

- Locks (used in the Dashboard to represent the details of locked tokens):
```
{
  id: "1",           // Unique ID for the lock
  tokenId: "1001",   // Token ID of the locked asset
  amount: 50,        // Amount of tokens locked
  duration: "30 days", // Duration of the lock
  status: "Locked"   // Status of the lock
}
```

- NFTs (each NFT corresponds to a lock and contains metadata about it):
```
{
  id: "NFT1",        // Unique NFT ID
  lockId: "1",       // ID of the lock this NFT corresponds to
  description: "NFT representing 50 tokens locked for 30 days", // Metadata description
}
```
Please also add an image attribute for NFT mock data.

Each NFTCard should display details fetched from the `getNFTs` method.

[ Hard Difficulty - Frontend, NFTs ]

### PR DESCRIPTION
**Pull request by petersdt**
Closes #3 

 - [x] Refactor Dashboard to display NFT metadata in a visually structured format.
 - [x] Link each NFT to its corresponding lock in the mock data.
 - [x] Create a better reusable NFTCard component to display NFT metadata:
NFT ID
Lock details (Token ID, Amount, Duration)
 - [x] Replace the plain list of NFTs with a styled grid of NFTCard components.
 
 
Mock

### CODE REVIEW

**Review by tekkac — COMMENTED** [review]
Great job, looks good.
Minor things:
 - could you tick what you did in the check buttons of the issue to make sure you did everything?
 -Should we display a mock jpg image in order to make sure we replace the mock data by the actual at somne point?
 @julienbrs let me know if the above is still relevant

**Comment by petersdt** [comment]
@tekkac @julienbrs does this look good to you?

**Comment by julienbrs** [comment]
please add pictures as requested before @petersdt :)

**Comment by petersdt** [comment]
@julienbrs @tekkac done kindly review

**Pull request merged**
