### PR TITLE
feat: Change the locker page to create a form for locking tokens and …

### PR DESCRIPTION
**Pull request by DanielEmmanuel1**
- Create LockForm component with the following form fields:
 - Token ID input
 - Amount input 
 - Lock duration input
- Add form validation to ensure required fields are filled
- Implement confirmation modal to preview lock details before submission
- Style form and modal with glassmorphism design using Tailwind CSS
 - Replace solid backgrounds with transparent backdrop-blur effect
 - Add rounded corners and shadow for depth
 - Maintain consistent padding/spacing throughout

### CODE REVIEW

**Comment by DanielEmmanuel1** [comment]
@julienbrs Please review

**Comment by DanielEmmanuel1** [comment]
Okay let me get on that immediately

**Comment by DanielEmmanuel1** [comment]
All done @schwepps 
Please review

**Review by schwepps — APPROVED** [review]
All good! Thanks @DanielEmmanuel1 !

**Pull request merged**
